# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test_client:
    working_directory: ~/game-catalog
    docker:
      - image: circleci/node:8.16
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          working_directory: ~/game-catalog/client
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          working_directory: ~/game-catalog/client
          command: npm run lint:js
      - run:
          working_directory: ~/game-catalog/client
          command: npm run lint:scss
      - run:
          working_directory: ~/game-catalog/client
          command: npm test

  test_server:
    working_directory: ~/game-catalog
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - deps1-{{ .Branch }}-
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      # run tests!
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make black lint test

workflows:
  version: 2
  test_client_and_server:
    jobs:
      - test_client
      - test_server
